
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: '12345678'
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: inventario_development

test:
  <<: *default
  database: inventario_test

production:
  <<: *default
  database: inventario_production
  username: ss
  password: <%= ENV['SS_DATABASE_PASSWORD'] %>



#default: &default
#  adapter: postgresql
#  encoding: unicode
#  username: developer
#  password: developer
#  host: localhost
#  pool: 5
#
#development:
#  <<: *default
#  database: inventario_development
#
#test:
#  <<: *default
#  database: inventario_test
#
#production:
#  <<: *default
#  database: inventario_production
#  username: inventario
#  password: <%= ENV['INVENTARIO_DATABASE_PASSWORD'] %>
